# Generated by Django 4.1.4 on 2022-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone_no", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "schedule_preference",
                    models.CharField(
                        choices=[
                            ("M1", "6-7 AM"),
                            ("M2", "7-8 AM"),
                            ("M3", "8-9 AM"),
                            ("N1", "5-6 PM"),
                        ],
                        max_length=2,
                    ),
                ),
                ("age", models.IntegerField(max_length=2)),
                ("upi_id", models.CharField(max_length=20)),
                ("amount", models.IntegerField(max_length=3)),
                ("date", models.DateField()),
            ],
        ),
    ]
