# Generated by Django 4.1.4 on 2022-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="age",
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="member",
            name="amount",
            field=models.IntegerField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_no",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="member",
            name="schedule_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M1", "6-7 AM"),
                    ("M2", "7-8 AM"),
                    ("M3", "8-9 AM"),
                    ("N1", "5-6 PM"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="upi_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
